# Generated by Django 2.2.2 on 2019-06-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
                ('p_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_mfd', models.DateField()),
                ('p_exd', models.DateField()),
            ],
        ),
    ]
